terraform {
  backend "gcs" {
    bucket = "terraform.george.black"
    prefix = "web"
  }
}

# Assets contains the finalized assets that will be uploaded to the site
resource "google_storage_bucket" "assets" {
  name                        = "web-assets.george.black"
  location                    = "US"
  force_destroy               = true
  project                     = "oceanblue-web"
  uniform_bucket_level_access = true

  versioning {
    enabled = true
  }
}

resource "google_storage_bucket" "assets_staging" {
  name                        = "web-assets-staging.george.black"
  location                    = "US"
  force_destroy               = true
  project                     = "oceanblue-web"
  uniform_bucket_level_access = true

  versioning {
    enabled = true
  }
}

# Snapshots contains point-in-time snapshots of built website files, generated by the web builder
resource "google_storage_bucket" "snapshots" {
  name                        = "web-snapshots.george.black"
  location                    = "US-SOUTH1"
  storage_class               = "ARCHIVE"
  force_destroy               = true
  project                     = "oceanblue-web"
  uniform_bucket_level_access = true

  versioning {
    enabled = false
  }
}

resource "google_storage_bucket" "snapshots_staging" {
  name                        = "web-snapshots-staging.george.black"
  location                    = "US-SOUTH1"
  storage_class               = "ARCHIVE"
  force_destroy               = true
  project                     = "oceanblue-web"
  uniform_bucket_level_access = true

  versioning {
    enabled = false
  }
}

# Service account for Web API service
resource "google_service_account" "web_api" {
  account_id   = "web-api"
  display_name = "API"
  description  = "Used by Web API Cloud Run service"
  project      = "oceanblue-web"
}

# Enable Web API to access secrets
resource "google_project_iam_member" "web_api_secret_access" {
  role    = "roles/secretmanager.secretAccessor"
  member  = "serviceAccount:${google_service_account.web_api.email}"
  project = "oceanblue-web"
}

# Enable Web API to access data in Cloud Firestore
resource "google_project_iam_member" "web_api_firestore_access" {
  role    = "roles/datastore.user"
  member  = "serviceAccount:${google_service_account.web_api.email}"
  project = "oceanblue-web"
}
